name: Java CI with Maven

on:
  pull_request:
    paths:
      - 'src/main/java/**/*.java'
      - 'src/test/java/**/*.java'
      - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile and run tests
        run: |
          find ./src/test/java -type f -name "*.java" > tests.txt
          javac -d out -cp ./out:./lib/junit-platform-console-standalone-1.9.3.jar:./lib/gson-2.10.1.jar @tests.txt
          java -cp out:./lib/junit-platform-console-standalone-1.9.3.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
